// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_triangulate
List cpp_triangulate(NumericMatrix points, Nullable<IntegerMatrix> edges_nullable, double min_dist_tolerance);
RcppExport SEXP _tulpaMesh_cpp_triangulate(SEXP pointsSEXP, SEXP edges_nullableSEXP, SEXP min_dist_toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type edges_nullable(edges_nullableSEXP);
    Rcpp::traits::input_parameter< double >::type min_dist_tolerance(min_dist_toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_triangulate(points, edges_nullable, min_dist_tolerance));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ruppert_refine
List cpp_ruppert_refine(NumericMatrix points, Nullable<IntegerMatrix> edges_nullable, double min_angle_deg, double max_area, int max_steiner, double min_dist_tolerance);
RcppExport SEXP _tulpaMesh_cpp_ruppert_refine(SEXP pointsSEXP, SEXP edges_nullableSEXP, SEXP min_angle_degSEXP, SEXP max_areaSEXP, SEXP max_steinerSEXP, SEXP min_dist_toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type edges_nullable(edges_nullableSEXP);
    Rcpp::traits::input_parameter< double >::type min_angle_deg(min_angle_degSEXP);
    Rcpp::traits::input_parameter< double >::type max_area(max_areaSEXP);
    Rcpp::traits::input_parameter< int >::type max_steiner(max_steinerSEXP);
    Rcpp::traits::input_parameter< double >::type min_dist_tolerance(min_dist_toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ruppert_refine(points, edges_nullable, min_angle_deg, max_area, max_steiner, min_dist_tolerance));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fem_matrices
List cpp_fem_matrices(NumericMatrix vertices, IntegerMatrix triangles);
RcppExport SEXP _tulpaMesh_cpp_fem_matrices(SEXP verticesSEXP, SEXP trianglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type triangles(trianglesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fem_matrices(vertices, triangles));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fem_matrices_parallel
List cpp_fem_matrices_parallel(NumericMatrix vertices, IntegerMatrix triangles);
RcppExport SEXP _tulpaMesh_cpp_fem_matrices_parallel(SEXP verticesSEXP, SEXP trianglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type triangles(trianglesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fem_matrices_parallel(vertices, triangles));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fem_matrices_p2
List cpp_fem_matrices_p2(NumericMatrix vertices, IntegerMatrix triangles6);
RcppExport SEXP _tulpaMesh_cpp_fem_matrices_p2(SEXP verticesSEXP, SEXP triangles6SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type triangles6(triangles6SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fem_matrices_p2(vertices, triangles6));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fem_matrices_nonstationary
List cpp_fem_matrices_nonstationary(NumericMatrix vertices, IntegerMatrix triangles, NumericVector kappa, NumericVector tau);
RcppExport SEXP _tulpaMesh_cpp_fem_matrices_nonstationary(SEXP verticesSEXP, SEXP trianglesSEXP, SEXP kappaSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type triangles(trianglesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fem_matrices_nonstationary(vertices, triangles, kappa, tau));
    return rcpp_result_gen;
END_RCPP
}
// cpp_projection_matrix
List cpp_projection_matrix(NumericMatrix obs_coords, NumericMatrix vertices, IntegerMatrix triangles);
RcppExport SEXP _tulpaMesh_cpp_projection_matrix(SEXP obs_coordsSEXP, SEXP verticesSEXP, SEXP trianglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type obs_coords(obs_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type triangles(trianglesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_projection_matrix(obs_coords, vertices, triangles));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fem_matrices_3d
List cpp_fem_matrices_3d(NumericMatrix vertices, IntegerMatrix triangles);
RcppExport SEXP _tulpaMesh_cpp_fem_matrices_3d(SEXP verticesSEXP, SEXP trianglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type triangles(trianglesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fem_matrices_3d(vertices, triangles));
    return rcpp_result_gen;
END_RCPP
}
// cpp_projection_matrix_3d
List cpp_projection_matrix_3d(NumericMatrix obs_coords, NumericMatrix vertices, IntegerMatrix triangles);
RcppExport SEXP _tulpaMesh_cpp_projection_matrix_3d(SEXP obs_coordsSEXP, SEXP verticesSEXP, SEXP trianglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type obs_coords(obs_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type triangles(trianglesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_projection_matrix_3d(obs_coords, vertices, triangles));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tulpaMesh_cpp_triangulate", (DL_FUNC) &_tulpaMesh_cpp_triangulate, 3},
    {"_tulpaMesh_cpp_ruppert_refine", (DL_FUNC) &_tulpaMesh_cpp_ruppert_refine, 6},
    {"_tulpaMesh_cpp_fem_matrices", (DL_FUNC) &_tulpaMesh_cpp_fem_matrices, 2},
    {"_tulpaMesh_cpp_fem_matrices_parallel", (DL_FUNC) &_tulpaMesh_cpp_fem_matrices_parallel, 2},
    {"_tulpaMesh_cpp_fem_matrices_p2", (DL_FUNC) &_tulpaMesh_cpp_fem_matrices_p2, 2},
    {"_tulpaMesh_cpp_fem_matrices_nonstationary", (DL_FUNC) &_tulpaMesh_cpp_fem_matrices_nonstationary, 4},
    {"_tulpaMesh_cpp_projection_matrix", (DL_FUNC) &_tulpaMesh_cpp_projection_matrix, 3},
    {"_tulpaMesh_cpp_fem_matrices_3d", (DL_FUNC) &_tulpaMesh_cpp_fem_matrices_3d, 2},
    {"_tulpaMesh_cpp_projection_matrix_3d", (DL_FUNC) &_tulpaMesh_cpp_projection_matrix_3d, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tulpaMesh(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
