# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_triangulate <- function(points, edges_nullable = NULL, min_dist_tolerance = 0.0) {
    .Call(`_tulpaMesh_cpp_triangulate`, points, edges_nullable, min_dist_tolerance)
}

cpp_ruppert_refine <- function(points, edges_nullable, min_angle_deg, max_area, max_steiner, min_dist_tolerance) {
    .Call(`_tulpaMesh_cpp_ruppert_refine`, points, edges_nullable, min_angle_deg, max_area, max_steiner, min_dist_tolerance)
}

cpp_fem_matrices <- function(vertices, triangles) {
    .Call(`_tulpaMesh_cpp_fem_matrices`, vertices, triangles)
}

cpp_fem_matrices_parallel <- function(vertices, triangles) {
    .Call(`_tulpaMesh_cpp_fem_matrices_parallel`, vertices, triangles)
}

cpp_fem_matrices_p2 <- function(vertices, triangles6) {
    .Call(`_tulpaMesh_cpp_fem_matrices_p2`, vertices, triangles6)
}

cpp_fem_matrices_nonstationary <- function(vertices, triangles, kappa, tau) {
    .Call(`_tulpaMesh_cpp_fem_matrices_nonstationary`, vertices, triangles, kappa, tau)
}

cpp_projection_matrix <- function(obs_coords, vertices, triangles) {
    .Call(`_tulpaMesh_cpp_projection_matrix`, obs_coords, vertices, triangles)
}

cpp_fem_matrices_3d <- function(vertices, triangles) {
    .Call(`_tulpaMesh_cpp_fem_matrices_3d`, vertices, triangles)
}

cpp_projection_matrix_3d <- function(obs_coords, vertices, triangles) {
    .Call(`_tulpaMesh_cpp_projection_matrix_3d`, obs_coords, vertices, triangles)
}

